"""initial migration

Revision ID: fbab40cdfa17
Revises: 
Create Date: 2023-11-22 17:09:42.896557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbab40cdfa17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stadiums',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('club', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('stadiums', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stadiums_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('reviews',
    sa.Column('reviewId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('accountUsername', sa.String(length=100), nullable=True),
    sa.Column('stadiumName', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['accountUsername'], ['user.username'], ),
    sa.ForeignKeyConstraint(['stadiumName'], ['stadiums.name'], ),
    sa.PrimaryKeyConstraint('reviewId')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_reviewId'), ['reviewId'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_reviewId'))

    op.drop_table('reviews')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('stadiums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stadiums_name'))

    op.drop_table('stadiums')
    # ### end Alembic commands ###
